server:
  port: 9000

spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://101.132.140.132/test?useUnicode=true&characterEncoding=utf8
    ip: 101.132.140.132
    port: 3306
    database: test
  thymeleaf:
    cache: false
    check-template: false
    mode: LEGACYHTML5
  kafka:
    producer:
      bootstrap-servers: localhost:9092

  ## Redis 配置
  ## Redis数据库索引（默认为0）
  redis:
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
#      max-active: 8
#      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      ## 连接池中的最大空闲连接
#      max-idle: 8
#      ## 连接池中的最小空闲连接
#      min-idle: 0
#      ## 连接超时时间（毫秒）
      timeout: 0
    ## Redis服务器连接密码（默认为空）
    password:
    database: 0


## Mybatis 配置
mybatis:
  mappe-locations: classpath:mapper/*.xml
  type-aliases-package: com.yannyao.demo.cache.demo2.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true               #二级缓存的全局开关

#集合kafka
yao:
  kafka:
    binder:
      brokers: localhost:9092
      zk-nodes: localhost:2181
    group: yao-group